spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev	   #开发环境
  application: 
    name: microservicecloud-config-coffee-123	
eno:
  hello: hello_dev_update
  world: world_dev_update
---
spring:
  profiles: test   #测试环境
  application: 
    name: microservicecloud-config-coffee-test
eno:
  hello: hello_test
  world: world_test

#  保存为UTF-8格式
