spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 8201
spring: 
  profiles: dev	   #开发环境
  application: 
    name: demo-commodity-config	
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:8761/eureka/
---
server: 
  port: 8202
spring: 
  profiles: test	   #测试环境
  application: 
    name: demo-commodity-config	
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-test.com:8761/eureka/

#  格式为UTF-8